apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-messaging-bridge
  namespace: svc-messaging-bridge
  labels:
    app: svc-messaging-bridge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svc-messaging-bridge
  template:
    metadata:
      labels:
        app: svc-messaging-bridge
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: svc-messaging-bridge
        image: ghcr.io/team-2-devs/svc-messaging-bridge:3
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: svc-messaging-bridge-secret
        readinessProbe:
          httpGet:
            path: health/ready
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: health/live
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30