apiVersion: v1
kind: Service
metadata:
  name: svc-messaging-bridge
  namespace: svc-messaging-bridge
spec:
  selector:
    app: svc-messaging-bridge
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080