apiVersion: v1
kind: Service
metadata:
  name: svc-ai-vision-adapter
  namespace: svc-ai-vision-adapter
spec:
  selector:
    app: svc-ai-vision-adapter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080