apiVersion: v1
kind: Service
metadata:
  name: svc-analysis-orchestrator
  namespace: svc-analysis-orchestrator
spec:
  selector:
    app.kubernetes.io/name: svc-analysis-orchestrator
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080