apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rabbitmq
  namespace: messaging
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: graph-gateway
          podSelector:
            matchLabels:
              app.kubernetes.io/name: graph-gateway
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: svc-analysis-orchestrator
          podSelector:
            matchLabels:
              app.kubernetes.io/name: svc-analysis-orchestrator
        - ipBlock:
            cidr: 0.0.0.0/0 # external client (svc-messaging-bridge running on host)
      ports:
        - protocol: TCP
          port: 5672 # AMQP
  egress:
  # Allow DNS to CoreDNS in kube-system
  - to:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: kube-system
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53